### ISSUE TITLE
Give an example for backwards lesson design

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#117]
The lesson now explains and has an exercise but does not show a tangible example.

**Comment by rkdarst** [comment]
What I was typing:

We should have or link to an example of the "backwards lesson design" that we expect people to make. In my room, it was a bit abstract and people were not starting off right or even following the principle very well.

Idea from @annefou: give an example form a CodeRefinery lesson (if we have any that are good enough to use...)  (I think we might need to make our own mini-lesson, say targeted to 15 minutes teaching time, and backwards design that - so that the design is understandable in a short time)

**Comment by rkdarst** [comment]
For this episode, I would also be happy if an outcome was "understand
badly designed lessons" - this may be a nice intermediate stepping
stone to "backwards design a lesson"

This fits with my learner persona of "someone who has to teach
hand-on topics sometimes, but this isn't their main job and they don't
have much training for it".  So, telling them what to look for makes
an improvement in what they do, and they can browse backwards design
when they need it.  I have many people who need this.

Or, the exercise could be written so that it teaches along with the
exercise, so that it can be done in breakout rooms without having to
have a lecture first.

**Comment by bast** [comment]
Followed up in #134 and implemented in #136.
