### ISSUE TITLE
Goal: give confidence

### ISSUE THREAD

**Issue by bast** [coderefinery/instructor-training#7]
(Just so I don't forget)

During panel session yesterday Lucy made a really good point: goal number one should be that we give participants confidence in the tools/topic. This is probably more important than giving "complete" knowledge or overview.

**Comment by bast** [comment]
@lucydot for me this was a very good and important point. Do you mind if I cite you on this sentence in our instructor training material? Is the quote accurate?

**Comment by rkdarst** [comment]
... and part of confidence is that you don't have to know everything to use (or teach) something.

**Comment by lucydot** [comment]
@bast absolutely, you can use any quote of mine, it'd be an honour :) I can't remember exactly what I said - perhaps to clarify the sentence a little it could be: "goal number one should be that we give participants the confidence to independently apply the tools or knowledge learnt. This is more important that giving a "complete" overview." 

This does give a different meaning to the statement you have posted - I was trying to make the point that teaching should be "student focused" rather than "getting through the curriculum focused". 

Additional points (these don't need to be included, I'm just putting them here as I'm thinking about it):
- for the large majority of topics we teach, there are many resources online which provide how-to guides or tutorials. And the Stack Overflow answer bank isn't getting any smaller. So we need to ask why do people attend in-person sessions if there is information freely available? --> my impression is that it is for confidence building, identity formation, perhaps signposting to resources.
- I think this also links with building a welcoming/inclusive environment: for example, imposter syndrome, which disproportionately affects under-represented groups ([link](https://www.ncda.org/aws/NCDA/pt/sd/news_article/245005/_PARENT/CC_layout_details/false)), can manifest as low self-confidence --> building the confidence of students in the classroom may lead to a more diverse community.
- This isn't new, the role of confidence in learning is something learnt about in teacher training in the UK (I need to dig out my old notes).

I should try and find more evidence in the literature for these statements at some point, as at the moment they are formed mostly from personal experience in the classroom.

**Comment by bast** [comment]
Thanks a lot for very good points! Indeed I have heard the opinion: 'Why should we organize a Python course? There are so many excellent courses and videos on the internet.' I agree with your rephrased statement and also the arguments you gave. Thank you!

**Comment by lucydot** [comment]
@rkdarst : to your comments - yes! and linking to that, the confidence to share our code when we know it's not perfect (not _nearly_ perfect)
